server:
  port: 8080
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: ms-vehiculo
          uri: lb://ms-vehiculo:8090
          predicates:
            - Path=/api/v1/vehiculos/**
      routes:
        - id: ms-detalle
          uri: lb://ms-detalle:8091
          predicates:
            - Path=/api/v1/detalles/**